### ISSUE TITLE
more checkers (and categories)

### ISSUE THREAD

**Issue by DanielRuf** [Brunty/awesome-checker-services#16]
I have a list with more checker services for example for DNS, IP, mail and other things.

## DNS https://github.com/Brunty/awesome-checker-services/pull/25
- [x] http://bgp.he.net (free, ASN, IP, Whois, Prefixes, Peers, ...)
- [x] http://ipv6-test.com/validate.php (free)
- [x] http://www.dnsstuff.com/tools (free)
- [x] http://www.ipvoid.com (free)
- [x] https://dnschecker.org (free)
- [x] https://ip6.nl (free)
- [x] https://mxtoolbox.com/SuperTool.aspx (free)
- [x] https://tools.keycdn.com (free)
- [x] https://toolbox.googleapps.com/apps/dig (free)
- [x] https://toolbox.googleapps.com/apps/checkmx (free)
- [x] https://www.ultratools.com (free)
## Browser Testing https://github.com/Brunty/awesome-checker-services/pull/26
- [x] http://browsershots.org (free)
- [x] https://saucelabs.com (free trial, free for open source projects, paid)
- [x] https://testingbot.com (free trial, free for open source projects, paid)
## Mail Configuration https://github.com/Brunty/awesome-checker-services/pull/27
- [x] http://verify-email.org (free, paid plans)
- [x] http://www.verifyemailaddress.org (free, paid bulk)
- [x] https://email-checker.net (free, paid premium plans)
- [x] https://hunter.io/email-verifier (free, paid)
- [x] https://tools.verifyemailaddress.io (free, paid API)
## Mail Testing https://github.com/Brunty/awesome-checker-services/pull/28
- [x] https://www.campaignmonitor.com (paid)
- [x] https://www.emailonacid.com (free trial, paid)
- [x] http://www.emailreach.com (free trial, paid)
- [x] https://litmus.com/email-testing (free trial, paid)
- [x] http://previewmyemail.com (paid)
- [x] https://putsmail.com (free)
## URL Analysis https://github.com/Brunty/awesome-checker-services/pull/29
- [x] http://urlquery.net (free)
- [x] https://urlscan.io (free)
## Website Performance https://github.com/Brunty/awesome-checker-services/pull/30
- [x] http://www.monitis.com/pageload (free)
- [x] https://testmysite.withgoogle.com (free)
- [x] https://toolbox.googleapps.com/apps/har_analyzer (free)
- [x] https://www.uptrends.com/tools/website-speed-test (free, paid)
- [x] https://www.webpagetest.org (free)
- [x] http://yellowlab.tools (free)
## Security https://github.com/Brunty/awesome-checker-services/pull/31
- [x] https://crt.sh (free)
- [x] https://csp-evaluator.withgoogle.com (free)
- [x] https://hackertarget.com (free, paid)
- [x] http://www.isithacked.com (free)
- [x] https://www.magereport.com (free)
- [x] https://report-uri.io/home/tools (free)
- [x] https://sshcheck.com (free)
- [x] https://ssldecoder.org (free)

**Comment by Brunty** [comment]
Fantastic! Thanks! 👍

**Comment by DanielRuf** [comment]
Assembled the first list without duplicates (URLs which are already in the readme).

Will split it into (new) categories in the initial comment in the next days, evaluate and add additional information (description, free / paid) and prepare a few PRs in the next days.

**Comment by Brunty** [comment]
Fantastic 👍 thanks so much for the work!

**Comment by DanielRuf** [comment]
Sorry for the late response. Split it into the first categories.

What do you think? Does it look good so far, how would you categorise them? I am open for any opinions.

Will add further details (free / paid, description) in the next days and try to split it into better categories or find better category names.

**Comment by Brunty** [comment]
@DanielRuf they look good to me! Thanks for such an awesome list 👍  it's much appreciated.

**Comment by DanielRuf** [comment]
Sorry for the late response. Added the prive information. The descriptions are next. And I could have some more final URLs.

Then we can decide which should be added as many provide the same features.

**Comment by Brunty** [comment]
@DanielRuf no worries about the late responses, in your own time :)

As for providing the same features, I'm not overly fussed if some provide the same features - lots of services out there do!

**Comment by renatonascalves** [comment]
Consider adding: https://testmysite.withgoogle.com/intl/en-gb new kid on the block

**Comment by Brunty** [comment]
@renatonascalves oh, nice! Didn't know about that one, I can add it, or you're welcome to put a PR in if you want to get that sweet sweet contributor goodness :)

**Comment by renatonascalves** [comment]
It's a brand new service from Google, but really interesting. Specially to "sell" to clients the importance of performance. Gonna send  a PR. 

Thanks for considering! :)

**Comment by DanielRuf** [comment]
Uses webpagetest. Lighthouse and sitespeed.io might be useful too if they are not yet in the list. I'll try to make some PRs this weekend.

**Comment by Brunty** [comment]
@DanielRuf thank you so much for all of these! <3

**Comment by DanielRuf** [comment]
@Brunty you are welcome!

All are now in the readme. Improvements regarding the descriptions are very welcome. Also if some tools may be duplicate and removed (better to have more in some cases as many have some rate limits).

Closing this issue as all PRs are merged.
