### ISSUE TITLE
Add uptime monitoring? 

### ISSUE THREAD

**Issue by ryanmaynard** [Brunty/awesome-checker-services#18]
Would uptime monitoring services be something you want to include?

- Uptime Robot
- StatusCake
- Uptrends
- ServiceUptime
- PagerDuty
- Apex.sh (Made by TJ Holowaychuk)
- StatusGator

Since there are hundreds of services in this category, I could understand if you didn't want to add them to your list. If you say yes, I'll proceed with adding them tomorrow.

**Comment by Brunty** [comment]
They could be useful, I'd say maybe limit it to some of the more popular / well known services? Open to discussion on this :)

**Comment by ryanmaynard** [comment]
I intend to follow your lead, Supreme Leader. I'm simply here to be sidekick and moral support. _salutes_

**Comment by renatonascalves** [comment]
There are too much options currently. I think the more free popular would be better. :)

**Comment by Talavasek** [comment]
I would like to add website monitoring too... [Avospy.com](url) check your web every 1-5 minutes and let you know instantly when something goes wrong via e-mail/SMS. You can set various Watchdogs for checking many parameters of your or your competitors websites. In the dashboard you will see all the important numbers and statuses. You can also analyze your website for free and then register with 14 day free trial.

**Comment by 1e4** [comment]
Was there any consensus on this? I can submit a PR for it if needed?

**Comment by Brunty** [comment]
@1e4 sure! Go for it! :D

**Comment by ryanmaynard** [comment]
Addressed in PR #45. Please don't hesitate to replace the ones I listed with other/better services. The ones I listed seemed to offer the most that I could find in their free tiers.

**Comment by 1e4** [comment]
Sorry hadn't gotten around to doing this after the last tweaks. Looks good @ryanmaynard
