### ISSUE TITLE
Consider including 'awesome' prefix in project name

### ISSUE THREAD

**Issue by alanpearce** [Brunty/awesome-checker-services#20]
It's common for these kinds of lists ([meta-list](https://github.com/sindresorhus/awesome)) to start with "awesome".  I think it might make it more discoverable.

**Comment by Brunty** [comment]
@alanpearce oooh, agreed - `awesome-checker-services` can be done, I think GitHub redirects old repo traffic to the new one as well?

**Comment by alanpearce** [comment]
According to the [documentation](https://help.github.com/articles/renaming-a-repository/), it does so for everything.

**Comment by Brunty** [comment]
Done!
