### ISSUE TITLE
https://www.whatsmydns.net/

### ISSUE THREAD

**Issue by joshbrw** [Brunty/awesome-checker-services#4]
Handy to know where DNS has propagated and where it hasn't

**Comment by Brunty** [comment]
Will add!
Also feel free to add it in as a PR yourself if you'd like, I'm easy either way 👍

**Comment by joshbrw** [comment]
Will PR later on today 🤙

**Comment by DanielRuf** [comment]
It's already in the readme, we can probably close this issue.

**Comment by joshbrw** [comment]
@DanielRuf Agreed. Was added 4 days after I posted this issue. Closing.
