### ISSUE TITLE
"contintents" in https://github.com/Brunty/awesome-checker-services#website-performance-

### ISSUE THREAD

**Issue by matkoniecz** [Brunty/awesome-checker-services#41]
https://github.com/Brunty/awesome-checker-services#website-performance-

**Comment by Brunty** [comment]
Thanks for spotting this @matkoniecz!

I'll fix it a bit later, but if you want to do so in the meantime and put in a PR for that sweet-sweet Open-Source-Helping good karma, feel free! :)

**Comment by 1e4** [comment]
@Brunty PR submitted as this wasn't changed.
